--------------------------------------------------------
--  DDL for Table LOGME
--------------------------------------------------------

  CREATE TABLE "REP_1"."LOGME" 
   (	"ID" NUMBER, 
	"JOB_START" DATE, 
	"JOB_END" DATE, 
	"JOB_AVG_RUNTIME" NUMBER, 
	"JOB_NO" NUMBER, 
	"JOB_NAME" VARCHAR2(50 BYTE), 
	"JOB_STATUS" VARCHAR2(50 BYTE), 
	"JOB_PROGRESS_PERCENT" NUMBER(3,0), 
	"JOB_INFO" VARCHAR2(1000 BYTE), 
	"JOB_FIRSTERROR" VARCHAR2(512 BYTE), 
	"JOB_NEXTERROR" VARCHAR2(512 BYTE), 
	"JOB_ID" NUMBER, 
	"JOB_SUB_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING ;
   
--------------------------------------------------------
--  DDL for Index PK_LOGME_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "REP_1"."PK_LOGME_ID" ON "REP_1"."LOGME" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
--------------------------------------------------------
--  DDL for Index LOGME_DATE_IDX
--------------------------------------------------------

  CREATE INDEX "REP_1"."LOGME_DATE_IDX" ON "REP_1"."LOGME" ("JOB_START", "JOB_END") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
--------------------------------------------------------
--  DDL for Index LOGME_I
--------------------------------------------------------

  CREATE INDEX "REP_1"."LOGME_I" ON "REP_1"."LOGME" ("JOB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
--------------------------------------------------------
--  DDL for Index LOGME_I2
--------------------------------------------------------

  CREATE INDEX "REP_1"."LOGME_I2" ON "REP_1"."LOGME" ("JOB_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ;
  
--------------------------------------------------------
--  DDL for Index LOGME_I3
--------------------------------------------------------

  CREATE INDEX "REP_1"."LOGME_I3" ON "REP_1"."LOGME" ("JOB_START") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
--------------------------------------------------------
--  Constraints for Table LOGME
--------------------------------------------------------

  ALTER TABLE "REP_1"."LOGME" ADD CONSTRAINT "PK_LOGME_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  ALTER TABLE "REP_1"."LOGME" MODIFY ("ID" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Trigger TR_LOGME_ID
--------------------------------------------------------

CREATE OR REPLACE TRIGGER "REP_1"."TR_LOGME_ID" 
BEFORE INSERT ON LOGME
    FOR EACH ROW
    BEGIN
      SELECT SEQ_LOGME_ID.NEXTVAL
      INTO   :new.ID
      FROM   dual;
    END;
    /
ALTER TRIGGER "REP_1"."TR_LOGME_ID" ENABLE;
